version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
# Log into AWS, build and push image to Amazon ECR
  build_and_push_image:
    jobs:
	- aws-ecr/build-and-push-image:
	  Test:
        machine:
          enabled: true
        steps:
          - run:
              name: Test.
              aws-access-key-id: AWS_ACCESS_KEY_ID
              aws-secret-access-key: AWS_SECRET_ACCESS_KEY
              region: AWS_DEFAULT_REGIO
              command: aws s3 cp s3://mypem-circleci
	      command: ssh -i circle.pem ubuntu@13.235.68.44 'echo "wellcome to innobit" ';
