orbs:
  node: circleci/node@2.0.2
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  Test:
    machine:
      enabled: true
    steps:
      - run:
          name: Test.
          command: ssh ubuntu@13.235.68.44 'echo "wellcome to innobit" ';
  QA:
    machine:
      enabled: true
    steps:
      - run:
          name: Test-QA.
          command: ssh ubuntu@13.235.68.44 'echo "wellcome to devops" ';
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - Test:
          filters:
            branches:
              only: test4
  build_and_deploy-qa:
    jobs:
      - QA:
          filters:
            branches:
              only: test5
