orbs:
  node: circleci/node@2.0.2
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  Test1:
    machine:
      enabled: true
    steps:
      - run:
          name: Test.
          command: ssh ec2-user@ec2-13-232-213-35.ap-south-1.compute.amazonaws.com 'echo "Wellcome to innobit"';
  Test2:
    machine:
      enabled: true
    steps:
      - run:
          name: Test.
          command: ssh ec2-user@ec2-13-232-213-35.ap-south-1.compute.amazonaws.com 'echo "Wellcome to Devops team"';
version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - Test:
          filters:
            branches:
              only: test4